### ISSUE TITLE
Docs.rs build failing

### ISSUE THREAD

**Issue by sajattack** [atsamd-rs/atsamd#24]
![img](https://i.imgur.com/bBREdMc.png)
Also the github.io keeps crashing my tabs.

**Comment by wez** [comment]
Yeah, it's not specific to us; the problem is that docs.rs only builds docs with the 1.28 stable compiler and that's not really compatible with the embedded rust ecosystem today:

```
error[E0658]: use of unstable library feature 'proc_macro' (see issue #38356)
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.19/src/unstable.rs:69:44
   |
69 |         let works = panic::catch_unwind(|| proc_macro::Span::call_site()).is_ok();
   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(proc_macro)] to the crate attributes to enable
```

https://docs.rs/crate/atsamd21-hal/0.2.1/builds/117065

This is one of the reasons why I set up the automated build and publish to github.io
